AWSTemplateFormatVersion: "2010-09-09"
Description: "Lambda function to input data into DynamoDB"

Parameters:
  LambdaSecurityGroup:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /LambdaSecurityGroup
  WebS3BucketName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /WebS3BucketName
  CodeS3Bucket:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /CodeS3BucketName
  basicSNSTopicArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /basicSNSTopic

Resources:
  ApiGwLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: "part2-lambda-login-data"
      Runtime: provided.al2
      Handler: bootstrap
      Code:
        S3Bucket: !Ref CodeS3Bucket
        S3Key: "lambda/part2-lambda-login-data.zip"
      Timeout: 60
      MemorySize: 128
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/lambda-api-gateway-role"
      Environment:
        Variables:
          ACCOUNT_ID: !Ref AWS::AccountId
          WebS3BUCKET: !Ref WebS3BucketName
          SNS_TOPIC_ARN: !Ref basicSNSTopicArn

  SSMLambdaFunctionName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /ApiGWLambdaFunctionName
      Type: String
      Value: !Ref ApiGwLambdaFunction

  SSMLambdaFunctionArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /ApiGWLambdaFunctionArn
      Type: String
      Value: !GetAtt ApiGwLambdaFunction.Arn
